server:
  port: 8081
spring:
  datasource:
    username: root
    password: Sharada@123
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  main:
      allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "sharadafalane2002@gmail.com"
    password: "add app password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
project:
  poster: poster/

base:
   url: "http://localhost:8081"

